### ISSUE TITLE
unable to deploy on heroku

### ISSUE THREAD

**Issue by zeeshanweb-official** [jm-shi/MERN-Social-Network#5]
hi sir..
i used this boilerplate and changed the client app and also the things in express server...
i deployed it on heroku but its not working fine...
its just serving the static files no get or post api is working...
kindly help me.

**Comment by jm-shi** [comment]
Hey, if the API calls aren't working then the database credentials might be invalid. Did you add REACT_APP_DB_URI and REACT_APP_JWT_KEY as config variables on Heroku? I used mLab to set up the database a while back, but it looks like they closed new account creation a year ago. Alternatively you can now create a cluster on MongoDB Atlas and paste its connection string as the value for REACT_APP_DB_URI. REACT_APP_JWT_KEY could be set to any string.

**Comment by zeeshanweb-official** [comment]
sir i found the solution...
the folder structure you made is not good...
and the main issue was in the package.json file...
there is a script heroku postbuild or something like that...
it runs and made a build of client project...
heroku doesnt care about it and deployed the client build as the main
project...
i deleted that script and it is now working fine

*Muhammad Awais Zeeshan*

+92307-4018-289
