### ISSUE TITLE
how to deploy it on heroku server

### ISSUE THREAD

**Issue by zeeshanweb-official** [jm-shi/MERN-Social-Network#6]
sir kindly guide me through the steps how can i deploy it on heroku...
i am unable to do so

**Comment by zeeshanweb-official** [comment]
i am facing issues...
i am trying to deploy it on heroku...
link is https://dashboard.heroku.com/apps/leyla-memories
but only the react app is being deployed not the server of the app...

**Comment by jm-shi** [comment]
I updated the setup instructions in the README; hope that could be of help.
